# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(586, 665)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.line_IP = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_IP.setFont(font)
        self.line_IP.setObjectName("line_IP")
        self.gridLayout.addWidget(self.line_IP, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.spin_subnet = QtWidgets.QSpinBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.spin_subnet.setFont(font)
        self.spin_subnet.setMinimum(1)
        self.spin_subnet.setMaximum(32)
        self.spin_subnet.setProperty("value", 24)
        self.spin_subnet.setObjectName("spin_subnet")
        self.gridLayout.addWidget(self.spin_subnet, 0, 3, 1, 1)
        self.btn_default_subnet = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_default_subnet.setFont(font)
        self.btn_default_subnet.setObjectName("btn_default_subnet")
        self.gridLayout.addWidget(self.btn_default_subnet, 0, 4, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 0, 0, 1, 5)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.lab_network_address = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lab_network_address.setFont(font)
        self.lab_network_address.setText("")
        self.lab_network_address.setObjectName("lab_network_address")
        self.gridLayout_2.addWidget(self.lab_network_address, 1, 2, 1, 1)
        self.btn_explain_net_address = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_explain_net_address.setFont(font)
        self.btn_explain_net_address.setCheckable(False)
        self.btn_explain_net_address.setObjectName("btn_explain_net_address")
        self.gridLayout_2.addWidget(self.btn_explain_net_address, 1, 4, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 2, 0, 1, 1)
        self.lab_broadcast_address = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lab_broadcast_address.setFont(font)
        self.lab_broadcast_address.setText("")
        self.lab_broadcast_address.setObjectName("lab_broadcast_address")
        self.gridLayout_2.addWidget(self.lab_broadcast_address, 2, 2, 1, 1)
        self.btn_explain_broadcast = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_explain_broadcast.setFont(font)
        self.btn_explain_broadcast.setCheckable(False)
        self.btn_explain_broadcast.setObjectName("btn_explain_broadcast")
        self.gridLayout_2.addWidget(self.btn_explain_broadcast, 2, 4, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 3, 1, 1, 1)
        self.lab_first_address = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lab_first_address.setFont(font)
        self.lab_first_address.setText("")
        self.lab_first_address.setObjectName("lab_first_address")
        self.gridLayout_2.addWidget(self.lab_first_address, 3, 2, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 3, 1, 1)
        self.btn_explain_first_node = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_explain_first_node.setFont(font)
        self.btn_explain_first_node.setCheckable(False)
        self.btn_explain_first_node.setObjectName("btn_explain_first_node")
        self.gridLayout_2.addWidget(self.btn_explain_first_node, 3, 4, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.lab_last_address = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lab_last_address.setFont(font)
        self.lab_last_address.setText("")
        self.lab_last_address.setObjectName("lab_last_address")
        self.gridLayout_2.addWidget(self.lab_last_address, 4, 2, 1, 1)
        self.btn_explain_last_node = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_explain_last_node.setFont(font)
        self.btn_explain_last_node.setCheckable(False)
        self.btn_explain_last_node.setObjectName("btn_explain_last_node")
        self.gridLayout_2.addWidget(self.btn_explain_last_node, 4, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 5, 0, 1, 1)
        self.lab_subnet_mask = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lab_subnet_mask.setFont(font)
        self.lab_subnet_mask.setText("")
        self.lab_subnet_mask.setObjectName("lab_subnet_mask")
        self.gridLayout_2.addWidget(self.lab_subnet_mask, 5, 2, 1, 1)
        self.btn_explain_subnet_mask = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_explain_subnet_mask.setFont(font)
        self.btn_explain_subnet_mask.setCheckable(False)
        self.btn_explain_subnet_mask.setObjectName("btn_explain_subnet_mask")
        self.gridLayout_2.addWidget(self.btn_explain_subnet_mask, 5, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 6, 0, 1, 1)
        self.lab_network_class = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lab_network_class.setFont(font)
        self.lab_network_class.setText("")
        self.lab_network_class.setObjectName("lab_network_class")
        self.gridLayout_2.addWidget(self.lab_network_class, 6, 2, 1, 1)
        self.btn_explain_address_class = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_explain_address_class.setFont(font)
        self.btn_explain_address_class.setCheckable(False)
        self.btn_explain_address_class.setObjectName("btn_explain_address_class")
        self.gridLayout_2.addWidget(self.btn_explain_address_class, 6, 4, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 7, 0, 1, 1)
        self.btn_explain_num_ips = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_explain_num_ips.setFont(font)
        self.btn_explain_num_ips.setCheckable(False)
        self.btn_explain_num_ips.setObjectName("btn_explain_num_ips")
        self.gridLayout_2.addWidget(self.btn_explain_num_ips, 7, 4, 1, 1)
        self.lab_num_ips = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.lab_num_ips.setFont(font)
        self.lab_num_ips.setText("")
        self.lab_num_ips.setObjectName("lab_num_ips")
        self.gridLayout_2.addWidget(self.lab_num_ips, 7, 2, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_39 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.gridLayout_3.addWidget(self.label_39, 0, 0, 1, 1)
        self.text_explanation = QtWidgets.QTextBrowser(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.text_explanation.setFont(font)
        self.text_explanation.setOpenExternalLinks(True)
        self.text_explanation.setObjectName("text_explanation")
        self.gridLayout_3.addWidget(self.text_explanation, 1, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 30))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuMenu.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PySub"))
        self.label.setText(_translate("MainWindow", "IP:"))
        self.line_IP.setText(_translate("MainWindow", "192.168.0.1"))
        self.label_3.setText(_translate("MainWindow", "/"))
        self.btn_default_subnet.setText(_translate("MainWindow", "Set default"))
        self.label_6.setText(_translate("MainWindow", "Network address:"))
        self.btn_explain_net_address.setText(_translate("MainWindow", "Explain"))
        self.label_8.setText(_translate("MainWindow", "Broadcast address:"))
        self.btn_explain_broadcast.setText(_translate("MainWindow", "Explain"))
        self.label_10.setText(_translate("MainWindow", "First usable address:"))
        self.btn_explain_first_node.setText(_translate("MainWindow", "Explain"))
        self.label_12.setText(_translate("MainWindow", "Last usable address:"))
        self.btn_explain_last_node.setText(_translate("MainWindow", "Explain"))
        self.label_13.setText(_translate("MainWindow", "Subnet mask (decimal):"))
        self.btn_explain_subnet_mask.setText(_translate("MainWindow", "Explain"))
        self.label_14.setText(_translate("MainWindow", "Network address class:"))
        self.btn_explain_address_class.setText(_translate("MainWindow", "Explain"))
        self.label_15.setText(_translate("MainWindow", "Number of free IPs:"))
        self.btn_explain_num_ips.setText(_translate("MainWindow", "Explain"))
        self.label_39.setText(_translate("MainWindow", "Explanation:"))
        self.menuMenu.setTitle(_translate("MainWindow", "&Menu"))
        self.actionAbout.setText(_translate("MainWindow", "&About"))

